### ISSUE TITLE
topoImgPath is not defined

### ISSUE THREAD

**Issue by rqx110** [xwenyuan/jtopo_topology#1]
bellow is not defined:

**topoImgPath**
https://github.com/xwenyuan/jtopo_topology/blob/c2040bf879f8836d41310ab2acfd9dba0b50d2fb/static/public/js/jtopo-editor.js#L997

**Timer**
https://github.com/xwenyuan/jtopo_topology/blob/c2040bf879f8836d41310ab2acfd9dba0b50d2fb/static/public/js/jtopo-editor.js#L545

**rootPath**
https://github.com/xwenyuan/jtopo_topology/blob/c2040bf879f8836d41310ab2acfd9dba0b50d2fb/network_topology.html#L644

and the `loadTopology` function has 3 parameters,
https://github.com/xwenyuan/jtopo_topology/blob/c2040bf879f8836d41310ab2acfd9dba0b50d2fb/static/public/js/jtopo-editor.js#L67

and also missing `util.js` in `static/public/js/`

please fix these errors, I clone this project, it can't run very well.

**Comment by xwenyuan** [comment]
Sorry for my mistake in latest commit, I've supplemented the util.js.
Now the problem of **topoImgPath**, **Timer**, and **rootPath** must be solved.

To explain the your last question about parameters in loadTopology function: my original intention was to design as you can change the background img when loading topology, then in my in practical use, I use a initial background img to save time. So the function is open, but I haven't use it in this demo project.

As you can see in this demo page, I've opened many functions as headbar tools like searching, topo mode change(preview/edit) and so on, **all this function were supported in jtopo-0.4.8-dev.js and jtopo-editor.js**, but in demo i just implement the most fundamental functions: drawing.

More comprehensive function implementation was in my second project(vue-branch, not yet) as you can see in the second gif. I'll split it from my big project when free in the future. Before that, anyone can try to realize them based on jtopo-0.4.8-dev.js and jtopo-editor.js.

Thanks for your attention and valuable suggestion. If you have any questions, feel free to ask, I'll respond as soon as I see it after work.

**Comment by rqx110** [comment]
Thanks.
